// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABsnIqHdIK2f3vInrW7_IRj2U0bzer8fk',
    appId: '1:74844177707:android:a9dbd2c919b0171f99716e',
    messagingSenderId: '74844177707',
    projectId: 'confiress',
    storageBucket: 'confiress.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3csUphp154BA911jWH3x7GOUq1sCNck8',
    appId: '1:74844177707:ios:59faa2fc361afcf599716e',
    messagingSenderId: '74844177707',
    projectId: 'confiress',
    storageBucket: 'confiress.firebasestorage.app',
    iosBundleId: 'com.example.confire',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBppgJDQDM4HK-bPi8CW9aVq6Wgo8z1iW8',
    appId: '1:74844177707:web:a027b2f739a89b5799716e',
    messagingSenderId: '74844177707',
    projectId: 'confiress',
    authDomain: 'confiress.firebaseapp.com',
    storageBucket: 'confiress.firebasestorage.app',
    measurementId: 'G-23DW9M52GJ',
  );

}